route:
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 30m
  receiver: 'slack'
receivers:
  - name: 'slack'
    slack_configs:
      - channel: '#general'
        api_url: "https://hooks.slack.com/services/XXXXX/xxxxx"
        send_resolved: true
        text: "{{ range .Alerts }} <!channel> {{ .Annotations.summary }}\n{{ .Annotations.description }}\n{{ end }}"
inhibit_rules:
  - source_match:
      severity: 'critical'
